kind: Route
apiVersion: v1
id: "${APPLICATION_NAME}-kieserver-https"
metadata:
  name: "${APPLICATION_NAME}-kieserver"
  labels:
    application: "${APPLICATION_NAME}"
    service: "${APPLICATION_NAME}-kieserver"
    app.kubernetes.io/managed-by: Helm
  annotations:
    description: Route for KIE Server's https service.
    meta.helm.sh/release-name: {{ .Values.APPLICATION_NAME }}
meta.helm.sh/release-namespace: {{ .Values.NAMESPACE }}
spec:
  host: "${KIE_SERVER_HOSTNAME_HTTPS}"
  to:
    name: "${APPLICATION_NAME}-kieserver"
  port:
    targetPort: https
  tls:
    termination: passthrough