kind: Service
apiVersion: v1
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
  selector:
    deploymentConfig: "{{.Values.APPLICATION_NAME}}-kieserver"
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
metadata:
  name: "{{.Values.APPLICATION_NAME}}-kieserver"
  labels:
    application: "{{.Values.APPLICATION_NAME}}"
    service: "{{.Values.APPLICATION_NAME}}-kieserver"
    app.kubernetes.io/managed-by: Helm
  annotations:
    description: All the KIE Server web server's ports.
    meta.helm.sh/release-name: {{ .Values.APPLICATION_NAME }}
    meta.helm.sh/release-namespace: {{ .Values.NAMESPACE }}