kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "insecure-{{.Values.APPLICATION_NAME}}-kieserver"
  labels:
    application: "{{.Values.APPLICATION_NAME}}"
    service: "{{.Values.APPLICATION_NAME}}-kieserver"
  annotations:
    description: Route for KIE Server's http service.
    haproxy.router.openshift.io/balance: source
spec:
  host: "{{.Values.KIE_SERVER_HOSTNAME_HTTP}}"
  to:
    name: "{{.Values.APPLICATION_NAME}}-kieserver"
  port:
    targetPort: http 