kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{.Values.APPLICATION_NAME}}-kieserver"
  annotations:
    meta.helm.sh/release-name: {{ .Values.APPLICATION_NAME }}
    meta.helm.sh/release-namespace: {{ .Values.NAMESPACE }}
  labels:
    application: "{{.Values.APPLICATION_NAME}}"
    app.kubernetes.io/managed-by: Helm