kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "{{ .Values.APPLICATION_NAME }}-kieserver"
      labels:
        application: "{{ .Values.APPLICATION_NAME }}"
        service: "{{ .Values.APPLICATION_NAME }}-kieserver"
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      source:
        type: Git
        git:
          uri: "{{ .Values.SOURCE_REPOSITORY_URL}}"
          ref: "{{ .Values.SOURCE_REPOSITORY_REF}}"
        contextDir: "{{ .Values.CONTEXT_DIR}}"
      strategy:
        type: Source
        sourceStrategy:
          env:
            - name: KIE_SERVER_CONTAINER_DEPLOYMENT
              value: "{{ .Values.KIE_SERVER_CONTAINER_DEPLOYMENT}}"
            - name: MAVEN_MIRROR_URL
              value: "{{ .Values.MAVEN_MIRROR_URL}}"
            - name: ARTIFACT_DIR
              value: "{{ .Values.ARTIFACT_DIR}}"
          forcePull: true
          from:
            kind: ImageStreamTag
            namespace: "{{ .Values.IMAGE_STREAM_NAMESPACE}}"
            name: "{{.Values.KIE_SERVER_IMAGE_STREAM_NAME}}:{{.Values.IMAGE_STREAM_TAG}}"
      output:
        to:
          kind: ImageStreamTag
          name: "{{ .Values.APPLICATION_NAME }}-kieserver:latest"
      triggers:
        - type: GitHub
          github:
            secret: "{{.Values.GITHUB_WEBHOOK_SECRET}}"
        - type: Generic
          generic:
            secret: "{{.Values.GENERIC_WEBHOOK_SECRET}}"
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange