apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "insecure-{{ .Values.APPLICATION_NAME }}-kieserver"
  labels:
    application: "{{ .Values.APPLICATION_NAME }}"
    service: "{{ .Values.APPLICATION_NAME }}-kieserver"
    app.kubernetes.io/managed-by: Helm
  annotations:
    description: Route for KIE Server's http service.
    haproxy.router.openshift.io/balance: source
    meta.helm.sh/release-name: {{ .Values.APPLICATION_NAME }}
    meta.helm.sh/release-namespace: {{ .Values.NAMESPACE }}
spec:
  host: "{{ .Values.KIE_SERVER_HOSTNAME_HTTP}}"
  to:
    kind: Service
    name: "{{ .Values.APPLICATION_NAME }}-kieserver"
  port:
    targetPort: http