--- 
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata: 
  annotations: 
    template.alpha.openshift.io/wait-for-ready: "true"
  labels: 
    application: "{{.Values.APPLICATION_NAME}}"
    service: "{{.Values.APPLICATION_NAME}}-kieserver"
  name: "{{.Values.APPLICATION_NAME}}-kieserver"
spec: 
  output: 
    to: 
      kind: ImageStreamTag
      name: "{{.Values.APPLICATION_NAME }}-kieserver:latest"
  source: 
    contextDir: "{{.Values.CONTEXT_DIR}}"
    git: 
      ref: "{{.Values.SOURCE_REPOSITORY_REF}}"
      uri: "{{.Values.SOURCE_REPOSITORY_URL}}"
    type: Git
    sourceSecret:
      name: jl-gitlab-token
  strategy: 
    sourceStrategy: 
      env: 
        - 
          name: KIE_SERVER_CONTAINER_DEPLOYMENT
          value: "{{.Values.KIE_SERVER_CONTAINER_DEPLOYMENT}}"
        - 
          name: MAVEN_MIRROR_URL
          value: "{{.Values.MAVEN_MIRROR_URL}}"
        - 
          name: ARTIFACT_DIR
          value: "{{.Values.ARTIFACT_DIR}}"
      forcePull: true
      from: 
        kind: ImageStreamTag
        name: "{{.Values.KIE_SERVER_IMAGE_STREAM_NAME}}:{{.Values.IMAGE_STREAM_TAG}}"
        namespace: "{{.Values.IMAGE_STREAM_NAMESPACE}}"
    type: Source